version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "> 10.17.56"
  - dependency-name: "@types/node"
    versions:
    - ">= 11.a, < 12"
  - dependency-name: "@types/node"
    versions:
    - ">= 12.a, < 13"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.21.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
  - dependency-name: ts-jest
    versions:
    - 26.5.2
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
